In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [ ]:
df = pd.read_csv("homeprices.csv")
df

In [ ]:
import math
median_bedroom = math.floor (df.bedrooms.median())
median_bedroom

In [ ]:
df.bedrooms = df.bedrooms.fillna(median_bedroom)
df

In [ ]:
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms', 'age']], df.price)

In [ ]:
reg.coef_

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [ ]:
df = pd.read_csv("homeprices.csv")
df

In [ ]:
import math
median_bedroom = math.floor (df.bedrooms.median())
median_bedroom

In [ ]:
df.bedrooms.fillna(median_bedroom)

In [ ]:
df.bedrooms = df.bedrooms.fillna(median_bedroom)
df

Now till here my data pre processing step is over

In [ ]:
from sklearn import linear_model


In [ ]:
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms', 'age']], df.price)

In [ ]:
reg.coef_

In [ ]:
reg.intercept_

In [ ]:
reg.predict([[3000, 3, 40]])

In [ ]:
137.25*3000+-26025*3+-6825*40+383724.99999999977

In [ ]:
reg.predict([[2500, 4, 5]])

In [ ]:
import numpy as np

def gradient_descent(x, y):
    m_curr = b_curr = 0
    iterations = 10000
    n = len(x)
    learning_rate = 0.08

    for i in range(iterations):
        y_predicted = m_curr * x + b_curr
        cost = (1/n) * sum([val**2 for val in (y - y_predicted)])
        md = -(2/n)*sum(x*(y - y_predicted))
        bd = -(2/n)*sum(y - y_predicted)
        m_curr = m_curr - learning_rate * md
        b_curr = b_curr - learning_rate * bd
        print("m {}, b {}, cost {}, iteration {}".format(m_curr, b_curr, cost, i))


x = np.array([1,2,3,4,5])
y = np.array([5,7,9,11,13])

gradient_descent(x, y)

In [ ]:
import pickle

In [ ]:
model = linear_model.LinearRegression()
model.fit(df[['area']], df.price)

In [ ]:
model.coef_

In [ ]:
model.intercept_

In [ ]:
model.predict([[5000]])

In [32]:
import pickle

In [33]:
with open('model_pickle', 'wb') as f:
    pickle.dump(model, f)

In [34]:
with open('model_pickle', 'rb') as f:
    mp = pickle.load(f)

In [38]:
mp.predict([[5000]])

c:\Users\vansh\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([846609.5890411])

In [41]:
pip install joblib


Note: you may need to restart the kernel to use updated packages.


In [42]:
import joblib

# Save model
joblib.dump(model, 'model.pkl')

# Load model
loaded_model = joblib.load('model.pkl')


In [43]:
from sklearn.externals import joblib

ImportError: cannot import name 'joblib' from 'sklearn.externals' (c:\Users\vansh\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\externals\__init__.py)

In [44]:
joblib.dump(model, 'model.joblib')

['model.joblib']

In [45]:
mj = joblib.load('model.joblib')

In [46]:
mj.predict([[5000]])

c:\Users\vansh\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([846609.5890411])

In [47]:
mj.coef_

array([134.07534247])

In [48]:
mj.intercept_

np.float64(176232.87671232875)