In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [9]:
df = pd.read_csv('townprices.csv')
df

town  area   price  monroe township  west windsor  robbinsville
0   monroe township  2600  550000                1             0           0.0
1   monroe township  3000  565000                1             0           0.0
2   monroe township  3200  610000                1             0           0.0
3   monroe township  3600  680000                1             0           0.0
4   monroe township  4000  725000                1             0           0.0
5      west windsor  2600  585000                0             1           0.0
6      west windsor  2800  615000                0             1           0.0
7      west windsor  3300  650000                0             1           0.0
8      west windsor  3600  710000                0             1           0.0
9      robbinsville  2600  575000                0             0           1.0
10     robbinsville  2900  600000                0             0           1.0
11     robbinsville  3100  620000                0             0           NaN
12     robbinsville  3600  695000                0             0           NaN

In [10]:
dummies = pd.get_dummies(df['town'])
dummies

monroe township  robbinsville  west windsor
0              True         False         False
1              True         False         False
2              True         False         False
3              True         False         False
4              True         False         False
5             False         False          True
6             False         False          True
7             False         False          True
8             False         False          True
9             False          True         False
10            False          True         False
11            False          True         False
12            False          True         False

In [12]:
merged = pd.concat([df, dummies], axis='columns')
merged

town  area   price  monroe township  west windsor  \
0   monroe township  2600  550000                1             0   
1   monroe township  3000  565000                1             0   
2   monroe township  3200  610000                1             0   
3   monroe township  3600  680000                1             0   
4   monroe township  4000  725000                1             0   
5      west windsor  2600  585000                0             1   
6      west windsor  2800  615000                0             1   
7      west windsor  3300  650000                0             1   
8      west windsor  3600  710000                0             1   
9      robbinsville  2600  575000                0             0   
10     robbinsville  2900  600000                0             0   
11     robbinsville  3100  620000                0             0   
12     robbinsville  3600  695000                0             0   

    robbinsville  monroe township  robbinsville  west windsor  
0            0.0             True         False         False  
1            0.0             True         False         False  
2            0.0             True         False         False  
3            0.0             True         False         False  
4            0.0             True         False         False  
5            0.0            False         False          True  
6            0.0            False         False          True  
7            0.0            False         False          True  
8            0.0            False         False          True  
9            1.0            False          True         False  
10           1.0            False          True         False  
11           NaN            False          True         False  
12           NaN            False          True         False

In [13]:
final = merged.drop(['town', 'west windsor'], axis='columns')
final

area   price  monroe township  robbinsville  monroe township  robbinsville
0   2600  550000                1           0.0             True         False
1   3000  565000                1           0.0             True         False
2   3200  610000                1           0.0             True         False
3   3600  680000                1           0.0             True         False
4   4000  725000                1           0.0             True         False
5   2600  585000                0           0.0            False         False
6   2800  615000                0           0.0            False         False
7   3300  650000                0           0.0            False         False
8   3600  710000                0           0.0            False         False
9   2600  575000                0           1.0            False          True
10  2900  600000                0           1.0            False          True
11  3100  620000                0           NaN            False          True
12  3600  695000                0           NaN            False          True

In [14]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [15]:
X = final.drop('price', axis='columns')
X

area  monroe township  robbinsville  monroe township  robbinsville
0   2600                1           0.0             True         False
1   3000                1           0.0             True         False
2   3200                1           0.0             True         False
3   3600                1           0.0             True         False
4   4000                1           0.0             True         False
5   2600                0           0.0            False         False
6   2800                0           0.0            False         False
7   3300                0           0.0            False         False
8   3600                0           0.0            False         False
9   2600                0           1.0            False          True
10  2900                0           1.0            False          True
11  3100                0           NaN            False          True
12  3600                0           NaN            False          True

In [16]:
y = final.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [18]:
from sklearn.ensemble import HistGradientBoostingRegressor

model = HistGradientBoostingRegressor()
model.fit(X, y)


HistGradientBoostingRegressor()

In [19]:
model.predict([[2800,0,1]])

c:\Users\vansh\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but HistGradientBoostingRegressor was fitted with feature names
  warnings.warn(


ValueError: X has 3 features, but HistGradientBoostingRegressor is expecting 5 features as input.

In [20]:
model.score(X, y)

0.0

In [21]:
df

town  area   price  monroe township  west windsor  robbinsville
0   monroe township  2600  550000                1             0           0.0
1   monroe township  3000  565000                1             0           0.0
2   monroe township  3200  610000                1             0           0.0
3   monroe township  3600  680000                1             0           0.0
4   monroe township  4000  725000                1             0           0.0
5      west windsor  2600  585000                0             1           0.0
6      west windsor  2800  615000                0             1           0.0
7      west windsor  3300  650000                0             1           0.0
8      west windsor  3600  710000                0             1           0.0
9      robbinsville  2600  575000                0             0           1.0
10     robbinsville  2900  600000                0             0           1.0
11     robbinsville  3100  620000                0             0           NaN
12     robbinsville  3600  695000                0             0           NaN

In [23]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [26]:
dfle = df
df.town = le.fit_transform(dfle['town'])
dfle

town  area   price  monroe township  west windsor  robbinsville
0      0  2600  550000                1             0           0.0
1      0  3000  565000                1             0           0.0
2      0  3200  610000                1             0           0.0
3      0  3600  680000                1             0           0.0
4      0  4000  725000                1             0           0.0
5      2  2600  585000                0             1           0.0
6      2  2800  615000                0             1           0.0
7      2  3300  650000                0             1           0.0
8      2  3600  710000                0             1           0.0
9      1  2600  575000                0             0           1.0
10     1  2900  600000                0             0           1.0
11     1  3100  620000                0             0           NaN
12     1  3600  695000                0             0           NaN

In [28]:
X = df[['town', 'area']].values
X

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]])

In [29]:
y = dfle.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [30]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()

In [33]:
X = ohe.fit_transform(X).toarray()
X

array([[0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        0., 1., 1., 0., 1., 0., 1., 0.],
       [0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 0., 1., 1., 0.],
       [0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 0., 1., 1., 0., 1., 0.],
       [1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 

In [35]:
X = X[:,1:]
X

array([[1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1.,
        1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 0., 1., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0.],
       [1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0.],
       [1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        0., 1., 1., 0., 1., 0.],
       [1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 0., 1., 1., 0.],
       [0., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0.,

In [36]:
model.fit(X, y)

HistGradientBoostingRegressor()

In [39]:
model.predict([[1, 0, 2800]])

ValueError: X has 3 features, but HistGradientBoostingRegressor is expecting 22 features as input.